replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/PROJECT_ID/app-images/frontend
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: github-actions-deployer@PROJECT_ID.iam.gserviceaccount.com
  name: "frontend-sa"
